<?php
$array = 
array (
  'results' => 
  array (
    array (
      'text' => 'Afganistán',
      'name' => 'Afghanistan',
      'iso2' => 'AF',
      'iso3' => 'AFG',
      'id' => 93,
    ),
    array (
      'text' => 'Albania',
      'name' => 'Albania',
      'iso2' => 'AL',
      'iso3' => 'ALB',
      'id' => 355,
    ),
    array (
      'text' => 'Alemania',
      'name' => 'Germany',
      'iso2' => 'DE',
      'iso3' => 'DEU',
      'id' => 49,
    ),
    array (
      'text' => 'Algeria',
      'name' => 'Algeria',
      'iso2' => 'DZ',
      'iso3' => 'DZA',
      'id' => 213,
    ),
    array (
      'text' => 'Andorra',
      'name' => 'Andorra',
      'iso2' => 'AD',
      'iso3' => 'AND',
      'id' => 376,
    ),
    array (
      'text' => 'Angola',
      'name' => 'Angola',
      'iso2' => 'AO',
      'iso3' => 'AGO',
      'id' => 244,
    ),
    array (
      'text' => 'Anguila',
      'name' => 'Anguilla',
      'iso2' => 'AI',
      'iso3' => 'AIA',
      'id' => '1 264',
    ),
    array (
      'text' => 'Antártida',
      'name' => 'Antarctica',
      'iso2' => 'AQ',
      'iso3' => 'ATA',
      'id' => 672,
    ),
    array (
      'text' => 'Antigua y Barbuda',
      'name' => 'Antigua and Barbuda',
      'iso2' => 'AG',
      'iso3' => 'ATG',
      'id' => '1 268',
    ),
    array (
      'text' => 'Antillas Neerlandesas',
      'name' => 'Netherlands Antilles',
      'iso2' => 'AN',
      'iso3' => 'ANT',
      'id' => 599,
    ),
    array (
      'text' => 'Arabia Saudita',
      'name' => 'Saudi Arabia',
      'iso2' => 'SA',
      'iso3' => 'SAU',
      'id' => 966,
    ),
    array (
      'text' => 'Argentina',
      'name' => 'Argentina',
      'iso2' => 'AR',
      'iso3' => 'ARG',
      'id' => 54,
    ),
    array (
      'text' => 'Armenia',
      'name' => 'Armenia',
      'iso2' => 'AM',
      'iso3' => 'ARM',
      'id' => 374,
    ),
    array (
      'text' => 'Aruba',
      'name' => 'Aruba',
      'iso2' => 'AW',
      'iso3' => 'ABW',
      'id' => 297,
    ),
    array (
      'text' => 'Australia',
      'name' => 'Australia',
      'iso2' => 'AU',
      'iso3' => 'AUS',
      'id' => 61,
    ),
    array (
      'text' => 'Austria',
      'name' => 'Austria',
      'iso2' => 'AT',
      'iso3' => 'AUT',
      'id' => 43,
    ),
    array (
      'text' => 'Azerbayán',
      'name' => 'Azerbaijan',
      'iso2' => 'AZ',
      'iso3' => 'AZE',
      'id' => 994,
    ),
    array (
      'text' => 'Bélgica',
      'name' => 'Belgium',
      'iso2' => 'BE',
      'iso3' => 'BEL',
      'id' => 32,
    ),
    array (
      'text' => 'Bahamas',
      'name' => 'Bahamas',
      'iso2' => 'BS',
      'iso3' => 'BHS',
      'id' => '1 242',
    ),
    array (
      'text' => 'Bahrein',
      'name' => 'Bahrain',
      'iso2' => 'BH',
      'iso3' => 'BHR',
      'id' => 973,
    ),
    array (
      'text' => 'Bangladesh',
      'name' => 'Bangladesh',
      'iso2' => 'BD',
      'iso3' => 'BGD',
      'id' => 880,
    ),
    array (
      'text' => 'Barbados',
      'name' => 'Barbados',
      'iso2' => 'BB',
      'iso3' => 'BRB',
      'id' => '1 246',
    ),
    array (
      'text' => 'Belice',
      'name' => 'Belize',
      'iso2' => 'BZ',
      'iso3' => 'BLZ',
      'id' => 501,
    ),
    array (
      'text' => 'Benín',
      'name' => 'Benin',
      'iso2' => 'BJ',
      'iso3' => 'BEN',
      'id' => 229,
    ),
    array (
      'text' => 'Bhután',
      'name' => 'Bhutan',
      'iso2' => 'BT',
      'iso3' => 'BTN',
      'id' => 975,
    ),
    array (
      'text' => 'Bielorrusia',
      'name' => 'Belarus',
      'iso2' => 'BY',
      'iso3' => 'BLR',
      'id' => 375,
    ),
    array (
      'text' => 'Birmania',
      'name' => 'Myanmar',
      'iso2' => 'MM',
      'iso3' => 'MMR',
      'id' => 95,
    ),
    array (
      'text' => 'Bolivia',
      'name' => 'Bolivia',
      'iso2' => 'BO',
      'iso3' => 'BOL',
      'id' => 591,
    ),
    array (
      'text' => 'Bosnia y Herzegovina',
      'name' => 'Bosnia and Herzegovina',
      'iso2' => 'BA',
      'iso3' => 'BIH',
      'id' => 387,
    ),
    array (
      'text' => 'Botsuana',
      'name' => 'Botswana',
      'iso2' => 'BW',
      'iso3' => 'BWA',
      'id' => 267,
    ),
    array (
      'text' => 'Brasil',
      'name' => 'Brazil',
      'iso2' => 'BR',
      'iso3' => 'BRA',
      'id' => 55,
    ),
    array (
      'text' => 'Brunéi',
      'name' => 'Brunei',
      'iso2' => 'BN',
      'iso3' => 'BRN',
      'id' => 673,
    ),
    array (
      'text' => 'Bulgaria',
      'name' => 'Bulgaria',
      'iso2' => 'BG',
      'iso3' => 'BGR',
      'id' => 359,
    ),
    array (
      'text' => 'Burkina Faso',
      'name' => 'Burkina Faso',
      'iso2' => 'BF',
      'iso3' => 'BFA',
      'id' => 226,
    ),
    array (
      'text' => 'Burundi',
      'name' => 'Burundi',
      'iso2' => 'BI',
      'iso3' => 'BDI',
      'id' => 257,
    ),
    array (
      'text' => 'Cabo Verde',
      'name' => 'Cape Verde',
      'iso2' => 'CV',
      'iso3' => 'CPV',
      'id' => 238,
    ),
    array (
      'text' => 'Camboya',
      'name' => 'Cambodia',
      'iso2' => 'KH',
      'iso3' => 'KHM',
      'id' => 855,
    ),
    array (
      'text' => 'Camerún',
      'name' => 'Cameroon',
      'iso2' => 'CM',
      'iso3' => 'CMR',
      'id' => 237,
    ),
    array (
      'text' => 'Canadá',
      'name' => 'Canada',
      'iso2' => 'CA',
      'iso3' => 'CAN',
      'id' => 1,
    ),
    array (
      'text' => 'Chad',
      'name' => 'Chad',
      'iso2' => 'TD',
      'iso3' => 'TCD',
      'id' => 235,
    ),
    array (
      'text' => 'Chile',
      'name' => 'Chile',
      'iso2' => 'CL',
      'iso3' => 'CHL',
      'id' => 56,
    ),
    array (
      'text' => 'China',
      'name' => 'China',
      'iso2' => 'CN',
      'iso3' => 'CHN',
      'id' => 86,
    ),
    array (
      'text' => 'Chipre',
      'name' => 'Cyprus',
      'iso2' => 'CY',
      'iso3' => 'CYP',
      'id' => 357,
    ),
    array (
      'text' => 'Ciudad del Vaticano',
      'name' => 'Vatican City State',
      'iso2' => 'VA',
      'iso3' => 'VAT',
      'id' => 39,
    ),
    array (
      'text' => 'Colombia',
      'name' => 'Colombia',
      'iso2' => 'CO',
      'iso3' => 'COL',
      'id' => 57,
    ),
    array (
      'text' => 'Comoras',
      'name' => 'Comoros',
      'iso2' => 'KM',
      'iso3' => 'COM',
      'id' => 269,
    ),
    array (
      'text' => 'Congo',
      'name' => 'Congo',
      'iso2' => 'CG',
      'iso3' => 'COG',
      'id' => 242,
    ),
    array (
      'text' => 'Congo',
      'name' => 'Congo',
      'iso2' => 'CD',
      'iso3' => 'COD',
      'id' => 243,
    ),
    array (
      'text' => 'Corea del Norte',
      'name' => 'North Korea',
      'iso2' => 'KP',
      'iso3' => 'PRK',
      'id' => 850,
    ),
    array (
      'text' => 'Corea del Sur',
      'name' => 'South Korea',
      'iso2' => 'KR',
      'iso3' => 'KOR',
      'id' => 82,
    ),
    array (
      'text' => 'Costa de Marfil',
      'name' => 'Ivory Coast',
      'iso2' => 'CI',
      'iso3' => 'CIV',
      'id' => 225,
    ),
    array (
      'text' => 'Costa Rica',
      'name' => 'Costa Rica',
      'iso2' => 'CR',
      'iso3' => 'CRI',
      'id' => 506,
    ),
    array (
      'text' => 'Croacia',
      'name' => 'Croatia',
      'iso2' => 'HR',
      'iso3' => 'HRV',
      'id' => 385,
    ),
    array (
      'text' => 'Cuba',
      'name' => 'Cuba',
      'iso2' => 'CU',
      'iso3' => 'CUB',
      'id' => 53,
    ),
    array (
      'text' => 'Dinamarca',
      'name' => 'Denmark',
      'iso2' => 'DK',
      'iso3' => 'DNK',
      'id' => 45,
    ),
    array (
      'text' => 'Dominica',
      'name' => 'Dominica',
      'iso2' => 'DM',
      'iso3' => 'DMA',
      'id' => '1 767',
    ),
    array (
      'text' => 'Ecuador',
      'name' => 'Ecuador',
      'iso2' => 'EC',
      'iso3' => 'ECU',
      'id' => 593,
    ),
    array (
      'text' => 'Egipto',
      'name' => 'Egypt',
      'iso2' => 'EG',
      'iso3' => 'EGY',
      'id' => 20,
    ),
    array (
      'text' => 'El Salvador',
      'name' => 'El Salvador',
      'iso2' => 'SV',
      'iso3' => 'SLV',
      'id' => 503,
    ),
    array (
      'text' => 'Emiratos Árabes Unidos',
      'name' => 'United Arab Emirates',
      'iso2' => 'AE',
      'iso3' => 'ARE',
      'id' => 971,
    ),
    array (
      'text' => 'Eritrea',
      'name' => 'Eritrea',
      'iso2' => 'ER',
      'iso3' => 'ERI',
      'id' => 291,
    ),
    array (
      'text' => 'Eslovaquia',
      'name' => 'Slovakia',
      'iso2' => 'SK',
      'iso3' => 'SVK',
      'id' => 421,
    ),
    array (
      'text' => 'Eslovenia',
      'name' => 'Slovenia',
      'iso2' => 'SI',
      'iso3' => 'SVN',
      'id' => 386,
    ),
    array (
      'text' => 'España',
      'name' => 'Spain',
      'iso2' => 'ES',
      'iso3' => 'ESP',
      'id' => 34,
    ),
    array (
      'text' => 'Estados Unidos de América',
      'name' => 'United States of America',
      'iso2' => 'US',
      'iso3' => 'USA',
      'id' => 1,
    ),
    array (
      'text' => 'Estonia',
      'name' => 'Estonia',
      'iso2' => 'EE',
      'iso3' => 'EST',
      'id' => 372,
    ),
    array (
      'text' => 'Etiopía',
      'name' => 'Ethiopia',
      'iso2' => 'ET',
      'iso3' => 'ETH',
      'id' => 251,
    ),
    array (
      'text' => 'Filipinas',
      'name' => 'Philippines',
      'iso2' => 'PH',
      'iso3' => 'PHL',
      'id' => 63,
    ),
    array (
      'text' => 'Finlandia',
      'name' => 'Finland',
      'iso2' => 'FI',
      'iso3' => 'FIN',
      'id' => 358,
    ),
    array (
      'text' => 'Fiyi',
      'name' => 'Fiji',
      'iso2' => 'FJ',
      'iso3' => 'FJI',
      'id' => 679,
    ),
    array (
      'text' => 'Francia',
      'name' => 'France',
      'iso2' => 'FR',
      'iso3' => 'FRA',
      'id' => 33,
    ),
    array (
      'text' => 'Gabón',
      'name' => 'Gabon',
      'iso2' => 'GA',
      'iso3' => 'GAB',
      'id' => 241,
    ),
    array (
      'text' => 'Gambia',
      'name' => 'Gambia',
      'iso2' => 'GM',
      'iso3' => 'GMB',
      'id' => 220,
    ),
    array (
      'text' => 'Georgia',
      'name' => 'Georgia',
      'iso2' => 'GE',
      'iso3' => 'GEO',
      'id' => 995,
    ),
    array (
      'text' => 'Ghana',
      'name' => 'Ghana',
      'iso2' => 'GH',
      'iso3' => 'GHA',
      'id' => 233,
    ),
    array (
      'text' => 'Gibraltar',
      'name' => 'Gibraltar',
      'iso2' => 'GI',
      'iso3' => 'GIB',
      'id' => 350,
    ),
    array (
      'text' => 'Granada',
      'name' => 'Grenada',
      'iso2' => 'GD',
      'iso3' => 'GRD',
      'id' => '1 473',
    ),
    array (
      'text' => 'Grecia',
      'name' => 'Greece',
      'iso2' => 'GR',
      'iso3' => 'GRC',
      'id' => 30,
    ),
    array (
      'text' => 'Groenlandia',
      'name' => 'Greenland',
      'iso2' => 'GL',
      'iso3' => 'GRL',
      'id' => 299,
    ),
    array (
      'text' => 'Guadalupe',
      'name' => 'Guadeloupe',
      'iso2' => 'GP',
      'iso3' => 'GLP',
      'id' => '',
    ),
    array (
      'text' => 'Guam',
      'name' => 'Guam',
      'iso2' => 'GU',
      'iso3' => 'GUM',
      'id' => '1 671',
    ),
    array (
      'text' => 'Guatemala',
      'name' => 'Guatemala',
      'iso2' => 'GT',
      'iso3' => 'GTM',
      'id' => 502,
    ),
    array (
      'text' => 'Guayana Francesa',
      'name' => 'French Guiana',
      'iso2' => 'GF',
      'iso3' => 'GUF',
      'id' => '',
    ),
    array (
      'text' => 'Guernsey',
      'name' => 'Guernsey',
      'iso2' => 'GG',
      'iso3' => 'GGY',
      'id' => '',
    ),
    array (
      'text' => 'Guinea',
      'name' => 'Guinea',
      'iso2' => 'GN',
      'iso3' => 'GIN',
      'id' => 224,
    ),
    array (
      'text' => 'Guinea Ecuatorial',
      'name' => 'Equatorial Guinea',
      'iso2' => 'GQ',
      'iso3' => 'GNQ',
      'id' => 240,
    ),
    array (
      'text' => 'Guinea-Bissau',
      'name' => 'Guinea-Bissau',
      'iso2' => 'GW',
      'iso3' => 'GNB',
      'id' => 245,
    ),
    array (
      'text' => 'Guyana',
      'name' => 'Guyana',
      'iso2' => 'GY',
      'iso3' => 'GUY',
      'id' => 592,
    ),
    array (
      'text' => 'Haití',
      'name' => 'Haiti',
      'iso2' => 'HT',
      'iso3' => 'HTI',
      'id' => 509,
    ),
    array (
      'text' => 'Honduras',
      'name' => 'Honduras',
      'iso2' => 'HN',
      'iso3' => 'HND',
      'id' => 504,
    ),
    array (
      'text' => 'Hong kong',
      'name' => 'Hong Kong',
      'iso2' => 'HK',
      'iso3' => 'HKG',
      'id' => 852,
    ),
    array (
      'text' => 'Hungría',
      'name' => 'Hungary',
      'iso2' => 'HU',
      'iso3' => 'HUN',
      'id' => 36,
    ),
    array (
      'text' => 'India',
      'name' => 'India',
      'iso2' => 'IN',
      'iso3' => 'IND',
      'id' => 91,
    ),
    array (
      'text' => 'Indonesia',
      'name' => 'Indonesia',
      'iso2' => 'ID',
      'iso3' => 'IDN',
      'id' => 62,
    ),
    array (
      'text' => 'Irán',
      'name' => 'Iran',
      'iso2' => 'IR',
      'iso3' => 'IRN',
      'id' => 98,
    ),
    array (
      'text' => 'Irak',
      'name' => 'Iraq',
      'iso2' => 'IQ',
      'iso3' => 'IRQ',
      'id' => 964,
    ),
    array (
      'text' => 'Irlanda',
      'name' => 'Ireland',
      'iso2' => 'IE',
      'iso3' => 'IRL',
      'id' => 353,
    ),
    array (
      'text' => 'Isla Bouvet',
      'name' => 'Bouvet Island',
      'iso2' => 'BV',
      'iso3' => 'BVT',
      'id' => '',
    ),
    array (
      'text' => 'Isla de Man',
      'name' => 'Isle of Man',
      'iso2' => 'IM',
      'iso3' => 'IMN',
      'id' => 44,
    ),
    array (
      'text' => 'Isla de Navidad',
      'name' => 'Christmas Island',
      'iso2' => 'CX',
      'iso3' => 'CXR',
      'id' => 61,
    ),
    array (
      'text' => 'Isla Norfolk',
      'name' => 'Norfolk Island',
      'iso2' => 'NF',
      'iso3' => 'NFK',
      'id' => '',
    ),
    array (
      'text' => 'Islandia',
      'name' => 'Iceland',
      'iso2' => 'IS',
      'iso3' => 'ISL',
      'id' => 354,
    ),
    array (
      'text' => 'Islas Bermudas',
      'name' => 'Bermuda Islands',
      'iso2' => 'BM',
      'iso3' => 'BMU',
      'id' => '1 441',
    ),
    array (
      'text' => 'Islas Caimán',
      'name' => 'Cayman Islands',
      'iso2' => 'KY',
      'iso3' => 'CYM',
      'id' => '1 345',
    ),
    array (
      'text' => 'Islas Cocos (Keeling)',
      'name' => 'Cocos (Keeling) Islands',
      'iso2' => 'CC',
      'iso3' => 'CCK',
      'id' => 61,
    ),
    array (
      'text' => 'Islas Cook',
      'name' => 'Cook Islands',
      'iso2' => 'CK',
      'iso3' => 'COK',
      'id' => 682,
    ),
    array (
      'text' => 'Islas de Åland',
      'name' => 'Åland Islands',
      'iso2' => 'AX',
      'iso3' => 'ALA',
      'id' => '',
    ),
    array (
      'text' => 'Islas Feroe',
      'name' => 'Faroe Islands',
      'iso2' => 'FO',
      'iso3' => 'FRO',
      'id' => 298,
    ),
    array (
      'text' => 'Islas Georgias del Sur y Sandwich del Sur',
      'name' => 'South Georgia and the South Sandwich Islands',
      'iso2' => 'GS',
      'iso3' => 'SGS',
      'id' => '',
    ),
    array (
      'text' => 'Islas Heard y McDonald',
      'name' => 'Heard Island and McDonald Islands',
      'iso2' => 'HM',
      'iso3' => 'HMD',
      'id' => '',
    ),
    array (
      'text' => 'Islas Maldivas',
      'name' => 'Maldives',
      'iso2' => 'MV',
      'iso3' => 'MDV',
      'id' => 960,
    ),
    array (
      'text' => 'Islas Malvinas',
      'name' => 'Falkland Islands (Malvinas)',
      'iso2' => 'FK',
      'iso3' => 'FLK',
      'id' => 500,
    ),
    array (
      'text' => 'Islas Marianas del Norte',
      'name' => 'Northern Mariana Islands',
      'iso2' => 'MP',
      'iso3' => 'MNP',
      'id' => '1 670',
    ),
    array (
      'text' => 'Islas Marshall',
      'name' => 'Marshall Islands',
      'iso2' => 'MH',
      'iso3' => 'MHL',
      'id' => 692,
    ),
    array (
      'text' => 'Islas Pitcairn',
      'name' => 'Pitcairn Islands',
      'iso2' => 'PN',
      'iso3' => 'PCN',
      'id' => 870,
    ),
    array (
      'text' => 'Islas Salomón',
      'name' => 'Solomon Islands',
      'iso2' => 'SB',
      'iso3' => 'SLB',
      'id' => 677,
    ),
    array (
      'text' => 'Islas Turcas y Caicos',
      'name' => 'Turks and Caicos Islands',
      'iso2' => 'TC',
      'iso3' => 'TCA',
      'id' => '1 649',
    ),
    array (
      'text' => 'Islas Ultramarinas Menores de Estados Unidos',
      'name' => 'United States Minor Outlying Islands',
      'iso2' => 'UM',
      'iso3' => 'UMI',
      'id' => '',
    ),
    array (
      'text' => 'Islas Vírgenes Británicas',
      'name' => 'Virgin Islands',
      'iso2' => 'VG',
      'iso3' => 'VG',
      'id' => '1 284',
    ),
    array (
      'text' => 'Islas Vírgenes de los Estados Unidos',
      'name' => 'United States Virgin Islands',
      'iso2' => 'VI',
      'iso3' => 'VIR',
      'id' => '1 340',
    ),
    array (
      'text' => 'Israel',
      'name' => 'Israel',
      'iso2' => 'IL',
      'iso3' => 'ISR',
      'id' => 972,
    ),
    array (
      'text' => 'Italia',
      'name' => 'Italy',
      'iso2' => 'IT',
      'iso3' => 'ITA',
      'id' => 39,
    ),
    array (
      'text' => 'Jamaica',
      'name' => 'Jamaica',
      'iso2' => 'JM',
      'iso3' => 'JAM',
      'id' => '1 876',
    ),
    array (
      'text' => 'Japón',
      'name' => 'Japan',
      'iso2' => 'JP',
      'iso3' => 'JPN',
      'id' => 81,
    ),
    array (
      'text' => 'Jersey',
      'name' => 'Jersey',
      'iso2' => 'JE',
      'iso3' => 'JEY',
      'id' => '',
    ),
    array (
      'text' => 'Jordania',
      'name' => 'Jordan',
      'iso2' => 'JO',
      'iso3' => 'JOR',
      'id' => 962,
    ),
    array (
      'text' => 'Kazajistán',
      'name' => 'Kazakhstan',
      'iso2' => 'KZ',
      'iso3' => 'KAZ',
      'id' => 7,
    ),
    array (
      'text' => 'Kenia',
      'name' => 'Kenya',
      'iso2' => 'KE',
      'iso3' => 'KEN',
      'id' => 254,
    ),
    array (
      'text' => 'Kirgizstán',
      'name' => 'Kyrgyzstan',
      'iso2' => 'KG',
      'iso3' => 'KGZ',
      'id' => 996,
    ),
    array (
      'text' => 'Kiribati',
      'name' => 'Kiribati',
      'iso2' => 'KI',
      'iso3' => 'KIR',
      'id' => 686,
    ),
    array (
      'text' => 'Kuwait',
      'name' => 'Kuwait',
      'iso2' => 'KW',
      'iso3' => 'KWT',
      'id' => 965,
    ),
    array (
      'text' => 'Líbano',
      'name' => 'Lebanon',
      'iso2' => 'LB',
      'iso3' => 'LBN',
      'id' => 961,
    ),
    array (
      'text' => 'Laos',
      'name' => 'Laos',
      'iso2' => 'LA',
      'iso3' => 'LAO',
      'id' => 856,
    ),
    array (
      'text' => 'Lesoto',
      'name' => 'Lesotho',
      'iso2' => 'LS',
      'iso3' => 'LSO',
      'id' => 266,
    ),
    array (
      'text' => 'Letonia',
      'name' => 'Latvia',
      'iso2' => 'LV',
      'iso3' => 'LVA',
      'id' => 371,
    ),
    array (
      'text' => 'Liberia',
      'name' => 'Liberia',
      'iso2' => 'LR',
      'iso3' => 'LBR',
      'id' => 231,
    ),
    array (
      'text' => 'Libia',
      'name' => 'Libya',
      'iso2' => 'LY',
      'iso3' => 'LBY',
      'id' => 218,
    ),
    array (
      'text' => 'Liechtenstein',
      'name' => 'Liechtenstein',
      'iso2' => 'LI',
      'iso3' => 'LIE',
      'id' => 423,
    ),
    array (
      'text' => 'Lituania',
      'name' => 'Lithuania',
      'iso2' => 'LT',
      'iso3' => 'LTU',
      'id' => 370,
    ),
    array (
      'text' => 'Luxemburgo',
      'name' => 'Luxembourg',
      'iso2' => 'LU',
      'iso3' => 'LUX',
      'id' => 352,
    ),
    array (
      'text' => 'México',
      'name' => 'Mexico',
      'iso2' => 'MX',
      'iso3' => 'MEX',
      'id' => 52,
    ),
    array (
      'text' => 'Mónaco',
      'name' => 'Monaco',
      'iso2' => 'MC',
      'iso3' => 'MCO',
      'id' => 377,
    ),
    array (
      'text' => 'Macao',
      'name' => 'Macao',
      'iso2' => 'MO',
      'iso3' => 'MAC',
      'id' => 853,
    ),
    array (
      'text' => 'Macedônia',
      'name' => 'Macedonia',
      'iso2' => 'MK',
      'iso3' => 'MKD',
      'id' => 389,
    ),
    array (
      'text' => 'Madagascar',
      'name' => 'Madagascar',
      'iso2' => 'MG',
      'iso3' => 'MDG',
      'id' => 261,
    ),
    array (
      'text' => 'Malasia',
      'name' => 'Malaysia',
      'iso2' => 'MY',
      'iso3' => 'MYS',
      'id' => 60,
    ),
    array (
      'text' => 'Malawi',
      'name' => 'Malawi',
      'iso2' => 'MW',
      'iso3' => 'MWI',
      'id' => 265,
    ),
    array (
      'text' => 'Mali',
      'name' => 'Mali',
      'iso2' => 'ML',
      'iso3' => 'MLI',
      'id' => 223,
    ),
    array (
      'text' => 'Malta',
      'name' => 'Malta',
      'iso2' => 'MT',
      'iso3' => 'MLT',
      'id' => 356,
    ),
    array (
      'text' => 'Marruecos',
      'name' => 'Morocco',
      'iso2' => 'MA',
      'iso3' => 'MAR',
      'id' => 212,
    ),
    array (
      'text' => 'Martinica',
      'name' => 'Martinique',
      'iso2' => 'MQ',
      'iso3' => 'MTQ',
      'id' => '',
    ),
    array (
      'text' => 'Mauricio',
      'name' => 'Mauritius',
      'iso2' => 'MU',
      'iso3' => 'MUS',
      'id' => 230,
    ),
    array (
      'text' => 'Mauritania',
      'name' => 'Mauritania',
      'iso2' => 'MR',
      'iso3' => 'MRT',
      'id' => 222,
    ),
    array (
      'text' => 'Mayotte',
      'name' => 'Mayotte',
      'iso2' => 'YT',
      'iso3' => 'MYT',
      'id' => 262,
    ),
    array (
      'text' => 'Micronesia',
      'name' => 'Estados Federados de',
      'iso2' => 'FM',
      'iso3' => 'FSM',
      'id' => 691,
    ),
    array (
      'text' => 'Moldavia',
      'name' => 'Moldova',
      'iso2' => 'MD',
      'iso3' => 'MDA',
      'id' => 373,
    ),
    array (
      'text' => 'Mongolia',
      'name' => 'Mongolia',
      'iso2' => 'MN',
      'iso3' => 'MNG',
      'id' => 976,
    ),
    array (
      'text' => 'Montenegro',
      'name' => 'Montenegro',
      'iso2' => 'ME',
      'iso3' => 'MNE',
      'id' => 382,
    ),
    array (
      'text' => 'Montserrat',
      'name' => 'Montserrat',
      'iso2' => 'MS',
      'iso3' => 'MSR',
      'id' => '1 664',
    ),
    array (
      'text' => 'Mozambique',
      'name' => 'Mozambique',
      'iso2' => 'MZ',
      'iso3' => 'MOZ',
      'id' => 258,
    ),
    array (
      'text' => 'Namibia',
      'name' => 'Namibia',
      'iso2' => 'NA',
      'iso3' => 'NAM',
      'id' => 264,
    ),
    array (
      'text' => 'Nauru',
      'name' => 'Nauru',
      'iso2' => 'NR',
      'iso3' => 'NRU',
      'id' => 674,
    ),
    array (
      'text' => 'Nepal',
      'name' => 'Nepal',
      'iso2' => 'NP',
      'iso3' => 'NPL',
      'id' => 977,
    ),
    array (
      'text' => 'Nicaragua',
      'name' => 'Nicaragua',
      'iso2' => 'NI',
      'iso3' => 'NIC',
      'id' => 505,
    ),
    array (
      'text' => 'Niger',
      'name' => 'Niger',
      'iso2' => 'NE',
      'iso3' => 'NER',
      'id' => 227,
    ),
    array (
      'text' => 'Nigeria',
      'name' => 'Nigeria',
      'iso2' => 'NG',
      'iso3' => 'NGA',
      'id' => 234,
    ),
    array (
      'text' => 'Niue',
      'name' => 'Niue',
      'iso2' => 'NU',
      'iso3' => 'NIU',
      'id' => 683,
    ),
    array (
      'text' => 'Noruega',
      'name' => 'Norway',
      'iso2' => 'NO',
      'iso3' => 'NOR',
      'id' => 47,
    ),
    array (
      'text' => 'Nueva Caledonia',
      'name' => 'New Caledonia',
      'iso2' => 'NC',
      'iso3' => 'NCL',
      'id' => 687,
    ),
    array (
      'text' => 'Nueva Zelanda',
      'name' => 'New Zealand',
      'iso2' => 'NZ',
      'iso3' => 'NZL',
      'id' => 64,
    ),
    array (
      'text' => 'Omán',
      'name' => 'Oman',
      'iso2' => 'OM',
      'iso3' => 'OMN',
      'id' => 968,
    ),
    array (
      'text' => 'Países Bajos',
      'name' => 'Netherlands',
      'iso2' => 'NL',
      'iso3' => 'NLD',
      'id' => 31,
    ),
    array (
      'text' => 'Pakistán',
      'name' => 'Pakistan',
      'iso2' => 'PK',
      'iso3' => 'PAK',
      'id' => 92,
    ),
    array (
      'text' => 'Palau',
      'name' => 'Palau',
      'iso2' => 'PW',
      'iso3' => 'PLW',
      'id' => 680,
    ),
    array (
      'text' => 'Palestina',
      'name' => 'Palestine',
      'iso2' => 'PS',
      'iso3' => 'PSE',
      'id' => '',
    ),
    array (
      'text' => 'Panamá',
      'name' => 'Panama',
      'iso2' => 'PA',
      'iso3' => 'PAN',
      'id' => 507,
    ),
    array (
      'text' => 'Papúa Nueva Guinea',
      'name' => 'Papua New Guinea',
      'iso2' => 'PG',
      'iso3' => 'PNG',
      'id' => 675,
    ),
    array (
      'text' => 'Paraguay',
      'name' => 'Paraguay',
      'iso2' => 'PY',
      'iso3' => 'PRY',
      'id' => 595,
    ),
    array (
      'text' => 'Perú',
      'name' => 'Peru',
      'iso2' => 'PE',
      'iso3' => 'PER',
      'id' => 51,
    ),
    array (
      'text' => 'Polinesia Francesa',
      'name' => 'French Polynesia',
      'iso2' => 'PF',
      'iso3' => 'PYF',
      'id' => 689,
    ),
    array (
      'text' => 'Polonia',
      'name' => 'Poland',
      'iso2' => 'PL',
      'iso3' => 'POL',
      'id' => 48,
    ),
    array (
      'text' => 'Portugal',
      'name' => 'Portugal',
      'iso2' => 'PT',
      'iso3' => 'PRT',
      'id' => 351,
    ),
    array (
      'text' => 'Puerto Rico',
      'name' => 'Puerto Rico',
      'iso2' => 'PR',
      'iso3' => 'PRI',
      'id' => 1,
    ),
    array (
      'text' => 'Qatar',
      'name' => 'Qatar',
      'iso2' => 'QA',
      'iso3' => 'QAT',
      'id' => 974,
    ),
    array (
      'text' => 'Reino Unido',
      'name' => 'United Kingdom',
      'iso2' => 'GB',
      'iso3' => 'GBR',
      'id' => 44,
    ),
    array (
      'text' => 'República Centroafricana',
      'name' => 'Central African Republic',
      'iso2' => 'CF',
      'iso3' => 'CAF',
      'id' => 236,
    ),
    array (
      'text' => 'República Checa',
      'name' => 'Czech Republic',
      'iso2' => 'CZ',
      'iso3' => 'CZE',
      'id' => 420,
    ),
    array (
      'text' => 'República Dominicana',
      'name' => 'Dominican Republic',
      'iso2' => 'DO',
      'iso3' => 'DOM',
      'id' => '1 809',
    ),
    array (
      'text' => 'Reunión',
      'name' => 'Réunion',
      'iso2' => 'RE',
      'iso3' => 'REU',
      'id' => '',
    ),
    array (
      'text' => 'Ruanda',
      'name' => 'Rwanda',
      'iso2' => 'RW',
      'iso3' => 'RWA',
      'id' => 250,
    ),
    array (
      'text' => 'Rumanía',
      'name' => 'Romania',
      'iso2' => 'RO',
      'iso3' => 'ROU',
      'id' => 40,
    ),
    array (
      'text' => 'Rusia',
      'name' => 'Russia',
      'iso2' => 'RU',
      'iso3' => 'RUS',
      'id' => 7,
    ),
    array (
      'text' => 'Sahara Occidental',
      'name' => 'Western Sahara',
      'iso2' => 'EH',
      'iso3' => 'ESH',
      'id' => '',
    ),
    array (
      'text' => 'Samoa',
      'name' => 'Samoa',
      'iso2' => 'WS',
      'iso3' => 'WSM',
      'id' => 685,
    ),
    array (
      'text' => 'Samoa Americana',
      'name' => 'American Samoa',
      'iso2' => 'AS',
      'iso3' => 'ASM',
      'id' => '1 684',
    ),
    array (
      'text' => 'San Bartolomé',
      'name' => 'Saint Barthélemy',
      'iso2' => 'BL',
      'iso3' => 'BLM',
      'id' => 590,
    ),
    array (
      'text' => 'San Cristóbal y Nieves',
      'name' => 'Saint Kitts and Nevis',
      'iso2' => 'KN',
      'iso3' => 'KNA',
      'id' => '1 869',
    ),
    array (
      'text' => 'San Marino',
      'name' => 'San Marino',
      'iso2' => 'SM',
      'iso3' => 'SMR',
      'id' => 378,
    ),
    array (
      'text' => 'San Martín (Francia)',
      'name' => 'Saint Martin (French part)',
      'iso2' => 'MF',
      'iso3' => 'MAF',
      'id' => '1 599',
    ),
    array (
      'text' => 'San Pedro y Miquelón',
      'name' => 'Saint Pierre and Miquelon',
      'iso2' => 'PM',
      'iso3' => 'SPM',
      'id' => 508,
    ),
    array (
      'text' => 'San Vicente y las Granadinas',
      'name' => 'Saint Vincent and the Grenadines',
      'iso2' => 'VC',
      'iso3' => 'VCT',
      'id' => '1 784',
    ),
    array (
      'text' => 'Santa Elena',
      'name' => 'Ascensión y Tristán de Acuña',
      'iso2' => 'SH',
      'iso3' => 'SHN',
      'id' => 290,
    ),
    array (
      'text' => 'Santa Lucía',
      'name' => 'Saint Lucia',
      'iso2' => 'LC',
      'iso3' => 'LCA',
      'id' => '1 758',
    ),
    array (
      'text' => 'Santo Tomé y Príncipe',
      'name' => 'Sao Tome and Principe',
      'iso2' => 'ST',
      'iso3' => 'STP',
      'id' => 239,
    ),
    array (
      'text' => 'Senegal',
      'name' => 'Senegal',
      'iso2' => 'SN',
      'iso3' => 'SEN',
      'id' => 221,
    ),
    array (
      'text' => 'Serbia',
      'name' => 'Serbia',
      'iso2' => 'RS',
      'iso3' => 'SRB',
      'id' => 381,
    ),
    array (
      'text' => 'Seychelles',
      'name' => 'Seychelles',
      'iso2' => 'SC',
      'iso3' => 'SYC',
      'id' => 248,
    ),
    array (
      'text' => 'Sierra Leona',
      'name' => 'Sierra Leone',
      'iso2' => 'SL',
      'iso3' => 'SLE',
      'id' => 232,
    ),
    array (
      'text' => 'Singapur',
      'name' => 'Singapore',
      'iso2' => 'SG',
      'iso3' => 'SGP',
      'id' => 65,
    ),
    array (
      'text' => 'Siria',
      'name' => 'Syria',
      'iso2' => 'SY',
      'iso3' => 'SYR',
      'id' => 963,
    ),
    array (
      'text' => 'Somalia',
      'name' => 'Somalia',
      'iso2' => 'SO',
      'iso3' => 'SOM',
      'id' => 252,
    ),
    array (
      'text' => 'Sri lanka',
      'name' => 'Sri Lanka',
      'iso2' => 'LK',
      'iso3' => 'LKA',
      'id' => 94,
    ),
    array (
      'text' => 'Sudáfrica',
      'name' => 'South Africa',
      'iso2' => 'ZA',
      'iso3' => 'ZAF',
      'id' => 27,
    ),
    array (
      'text' => 'Sudán',
      'name' => 'Sudan',
      'iso2' => 'SD',
      'iso3' => 'SDN',
      'id' => 249,
    ),
    array (
      'text' => 'Suecia',
      'name' => 'Sweden',
      'iso2' => 'SE',
      'iso3' => 'SWE',
      'id' => 46,
    ),
    array (
      'text' => 'Suiza',
      'name' => 'Switzerland',
      'iso2' => 'CH',
      'iso3' => 'CHE',
      'id' => 41,
    ),
    array (
      'text' => 'Surinám',
      'name' => 'Suriname',
      'iso2' => 'SR',
      'iso3' => 'SUR',
      'id' => 597,
    ),
    array (
      'text' => 'Svalbard y Jan Mayen',
      'name' => 'Svalbard and Jan Mayen',
      'iso2' => 'SJ',
      'iso3' => 'SJM',
      'id' => '',
    ),
    array (
      'text' => 'Swazilandia',
      'name' => 'Swaziland',
      'iso2' => 'SZ',
      'iso3' => 'SWZ',
      'id' => 268,
    ),
    array (
      'text' => 'Tadjikistán',
      'name' => 'Tajikistan',
      'iso2' => 'TJ',
      'iso3' => 'TJK',
      'id' => 992,
    ),
    array (
      'text' => 'Tailandia',
      'name' => 'Thailand',
      'iso2' => 'TH',
      'iso3' => 'THA',
      'id' => 66,
    ),
    array (
      'text' => 'Taiwán',
      'name' => 'Taiwan',
      'iso2' => 'TW',
      'iso3' => 'TWN',
      'id' => 886,
    ),
    array (
      'text' => 'Tanzania',
      'name' => 'Tanzania',
      'iso2' => 'TZ',
      'iso3' => 'TZA',
      'id' => 255,
    ),
    array (
      'text' => 'Territorio Británico del Océano Índico',
      'name' => 'British Indian Ocean Territory',
      'iso2' => 'IO',
      'iso3' => 'IOT',
      'id' => '',
    ),
    array (
      'text' => 'Territorios Australes y Antárticas Franceses',
      'name' => 'French Southern Territories',
      'iso2' => 'TF',
      'iso3' => 'ATF',
      'id' => '',
    ),
    array (
      'text' => 'Timor Oriental',
      'name' => 'East Timor',
      'iso2' => 'TL',
      'iso3' => 'TLS',
      'id' => 670,
    ),
    array (
      'text' => 'Togo',
      'name' => 'Togo',
      'iso2' => 'TG',
      'iso3' => 'TGO',
      'id' => 228,
    ),
    array (
      'text' => 'Tokelau',
      'name' => 'Tokelau',
      'iso2' => 'TK',
      'iso3' => 'TKL',
      'id' => 690,
    ),
    array (
      'text' => 'Tonga',
      'name' => 'Tonga',
      'iso2' => 'TO',
      'iso3' => 'TON',
      'id' => 676,
    ),
    array (
      'text' => 'Trinidad y Tobago',
      'name' => 'Trinidad and Tobago',
      'iso2' => 'TT',
      'iso3' => 'TTO',
      'id' => '1 868',
    ),
    array (
      'text' => 'Tunez',
      'name' => 'Tunisia',
      'iso2' => 'TN',
      'iso3' => 'TUN',
      'id' => 216,
    ),
    array (
      'text' => 'Turkmenistán',
      'name' => 'Turkmenistan',
      'iso2' => 'TM',
      'iso3' => 'TKM',
      'id' => 993,
    ),
    array (
      'text' => 'Turquía',
      'name' => 'Turkey',
      'iso2' => 'TR',
      'iso3' => 'TUR',
      'id' => 90,
    ),
    array (
      'text' => 'Tuvalu',
      'name' => 'Tuvalu',
      'iso2' => 'TV',
      'iso3' => 'TUV',
      'id' => 688,
    ),
    array (
      'text' => 'Ucrania',
      'name' => 'Ukraine',
      'iso2' => 'UA',
      'iso3' => 'UKR',
      'id' => 380,
    ),
    array (
      'text' => 'Uganda',
      'name' => 'Uganda',
      'iso2' => 'UG',
      'iso3' => 'UGA',
      'id' => 256,
    ),
    array (
      'text' => 'Uruguay',
      'name' => 'Uruguay',
      'iso2' => 'UY',
      'iso3' => 'URY',
      'id' => 598,
    ),
    array (
      'text' => 'Uzbekistán',
      'name' => 'Uzbekistan',
      'iso2' => 'UZ',
      'iso3' => 'UZB',
      'id' => 998,
    ),
    array (
      'text' => 'Vanuatu',
      'name' => 'Vanuatu',
      'iso2' => 'VU',
      'iso3' => 'VUT',
      'id' => 678,
    ),
    array (
      'text' => 'Venezuela',
      'name' => 'Venezuela',
      'iso2' => 'VE',
      'iso3' => 'VEN',
      'id' => 58,
    ),
    array (
      'text' => 'Vietnam',
      'name' => 'Vietnam',
      'iso2' => 'VN',
      'iso3' => 'VNM',
      'id' => 84,
    ),
    array (
      'text' => 'Wallis y Futuna',
      'name' => 'Wallis and Futuna',
      'iso2' => 'WF',
      'iso3' => 'WLF',
      'id' => 681,
    ),
    array (
      'text' => 'Yemen',
      'name' => 'Yemen',
      'iso2' => 'YE',
      'iso3' => 'YEM',
      'id' => 967,
    ),
    array (
      'text' => 'Yibuti',
      'name' => 'Djibouti',
      'iso2' => 'DJ',
      'iso3' => 'DJI',
      'id' => 253,
    ),
    array (
      'text' => 'Zambia',
      'name' => 'Zambia',
      'iso2' => 'ZM',
      'iso3' => 'ZMB',
      'id' => 260,
    ),
    array (
      'text' => 'Zimbabue',
      'name' => 'Zimbabwe',
      'iso2' => 'ZW',
      'iso3' => 'ZWE',
      'id' => 263,
    ),
  ),
);


if(!empty($_REQUEST['q'])){
    foreach ($array as $k => &$valor){
        foreach($valor as $r => &$valor2){
            if(strstr($valor2['name'], ucwords($_REQUEST['q']))){
                $nv_valor[] = $valor2;
            }
        }
    }
    
    $array2['results'] = $nv_valor;
    
    
    echo json_encode($array2);
    exit;
}

echo json_encode($array);
exit;